name: Publish
on:
    release:
        types: [ created ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write

        steps:
            -   uses: actions/checkout@v2

            -   name: Setup JDK 8
                uses: actions/setup-java@v1
                with:
                    java-version: 1.8

            -   name: Validate Gradle wrapper
                uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

            -   name: Publish package
                run: ./gradlew publish
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
